---

###
### Assert defaults and cluster overwrites
###
- include_tasks: asserts.yml


###
### Empty array variables for each loop iteration
###
- set_fact:
    kops_utility_subnets: []
    kops_private_subnets: []


###
### Gather facts about existing infrastructure
###

# Returns:
# * kops_vpc_cidr
# * kops_vpc_id
- include_tasks: gather_facts_vpc.yml

# Returns:
# * kops_utility_subnets
- include_tasks: gather_facts_subnets_utility.yml
  loop_control:
    loop_var: az
  with_items:
    - "{{ cluster.az | default(kops_default_az) }}"

# Returns:
# * kops_private_subnets
- include_tasks: gather_facts_subnets_private.yml
  loop_control:
    loop_var: az
  with_items:
    - "{{ cluster.az | default(kops_default_az) }}"


###
### Create templates
###
- name: ensure project build directory is present
  file:
    state: directory
    path: "{{ kops_default_build_directory}}/{{ cluster.name }}"

- name: generate cluster.yml
  template:
    src: cluster.yml.j2
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/cluster.yml"
    mode: 0644

- name: generate ig-master.yml
  template:
    src: ig-master.yml.j2
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/ig-master.yml"
    mode: 0644

- name: generate ig-worker.yml
  template:
    src: ig-worker.yml.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/ig-worker.yml"
    mode: 0644

- name: generate ig-bastion.yml
  template:
    src: ig-bastion.yml.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/ig-bastion.yml"
    mode: 0644

- name: generate kops-create.sh
  template:
    src: kops-create.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-create.sh"
    mode: 0755

- name: generate kops-update.sh
  template:
    src: kops-update.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-update.sh"
    mode: 0755
