---

###
### Assert defaults and cluster overwrites
###
- include_tasks: asserts.yml


###
### Empty array variables for each loop iteration
###
- set_fact:
    kops_utility_subnets: []
    kops_private_subnets: []


###
### Gather facts about existing infrastructure
###

# Returns:
# * kops_vpc_cidr
# * kops_vpc_id
- include_tasks: gather_facts_vpc.yml

# Returns:
# * kops_utility_subnets
- include_tasks: gather_facts_subnets_utility.yml
  loop_control:
    loop_var: az
  with_items:
    - "{{ cluster.az | default(kops_default_az) }}"

# Returns:
# * kops_private_subnets
- include_tasks: gather_facts_subnets_private.yml
  loop_control:
    loop_var: az
  with_items:
    - "{{ cluster.az | default(kops_default_az) }}"


###
### Create templates
###
- name: ensure project build directory is present
  file:
    state: directory
    path: "{{ kops_default_build_directory}}/{{ cluster.name }}"

- name: generate cluster.yml
  template:
    src: cluster.yml.j2
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/cluster.yml"
    mode: 0644

- name: generate instance-groups.yml
  template:
    src: instance-groups.yml.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/instance-groups.yml"
    mode: 0644

- name: generate ssh-key.pub
  template:
    src: ssh-key.pub.j2
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/ssh-key.pub"
    mode: 0644

- name: generate kops-create.sh
  template:
    src: kops-create.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-create.sh"
    mode: 0755

- name: generate kops-update.sh
  template:
    src: kops-update.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-update.sh"
    mode: 0755

- name: generate kops-info.sh
  template:
    src: kops-info.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-info.sh"
    mode: 0755

- name: generate kops-delete.sh
  template:
    src: kops-delete.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-delete.sh"
    mode: 0755

- name: generate kubectl-context.sh
  template:
    src: kubectl-context.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kubectl-context.sh"
    mode: 0755

- name: diff generated cluster config against remote state store
  diff:
    source: "{{ lookup('template', 'cluster.yml.j2') }}"
    target: |
      {% if kops_aws_profile %}
      # If using boto_profile, make kops aware of it
      export AWS_PROFILE="{{ kops_aws_profile }}";
      {% endif %}
      # Don't fail to show that remote has nothing yet
      kops get cluster -o yaml \
        --state s3://{{ cluster.s3_bucket_name }} \
        --name {{ cluster.name }} || true
    source_type: string
    target_type: command
    diff: yaml
    diff_yaml_ignore: ['creationTimestamp']
  check_mode: False

- name: diff generated instance group config against remote state store
  diff:
    source: "{{ lookup('template', 'instance-groups.yml.j2') }}"
    target: |
      {% if kops_aws_profile %}
      # If using boto_profile, make kops aware of it
      export AWS_PROFILE="{{ kops_aws_profile }}";
      {% endif %}
      # Don't fail to show that remote has nothing yet
      kops get instancegroups -o yaml \
        --state s3://{{ cluster.s3_bucket_name }} \
        --name {{ cluster.name }} || true
    source_type: string
    target_type: command
    diff: yaml
    diff_yaml_ignore: ['creationTimestamp']
  check_mode: False

- name: diff ssh public key against remote state store
  diff:
    source: |
      bash -c "ssh-keygen -lE md5 -f <(echo '{{ lookup('template', 'ssh-key.pub.j2') }}')" \
        | awk '{ print $2}' | sed 's/^MD5://g'
    target: |
      {% if kops_aws_profile %}
      # If using boto_profile, make kops aware of it
      export AWS_PROFILE="{{ kops_aws_profile }}";
      {% endif %}
      # Don't fail to show that remote has nothing yet
      kops get secret admin --type SSHPublicKey -o table \
        --state s3://{{ cluster.s3_bucket_name }} \
        --name {{ cluster.name }} \
        | grep -Eo "[:a-f0-9]{16,}" || true
    source_type: command
    target_type: command
  check_mode: False
