---

###
### Assert defaults and cluster overwrites
###
- include_tasks: asserts.yml


###
### Empty array variables for each loop iteration
###
- set_fact:
    kops_utility_subnets: []
    kops_private_subnets: []


###
### Gather facts about existing infrastructure
###

# Returns:
# * kops_vpc_cidr
# * kops_vpc_id
- include_tasks: gather_facts_vpc.yml

# Returns:
# * kops_utility_subnets
- include_tasks: gather_facts_subnets_utility.yml
  loop_control:
    loop_var: az
  with_items:
    - "{{ cluster.az | default(kops_default_az) }}"

# Returns:
# * kops_private_subnets
- include_tasks: gather_facts_subnets_private.yml
  loop_control:
    loop_var: az
  with_items:
    - "{{ cluster.az | default(kops_default_az) }}"


###
### Create templates
###
- name: ensure project build directory is present
  file:
    state: directory
    path: "{{ kops_default_build_directory}}/{{ cluster.name }}"

- name: generate cluster.yml
  template:
    src: cluster.yml.j2
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/cluster.yml"
    mode: 0644

- name: generate instance-groups.yml
  template:
    src: instance-groups.yml.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/instance-groups.yml"
    mode: 0644

- name: generate ssh-key.pub
  template:
    src: ssh-key.pub.j2
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/ssh-key.pub"
    mode: 0644

- name: generate kops-create.sh
  template:
    src: kops-create.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-create.sh"
    mode: 0755

- name: generate kops-update.sh
  template:
    src: kops-update.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-update.sh"
    mode: 0755

- name: generate kops-info.sh
  template:
    src: kops-info.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-info.sh"
    mode: 0755

- name: generate kops-delete.sh
  template:
    src: kops-delete.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-delete.sh"
    mode: 0755

- name: generate kubectl-context.sh
  template:
    src: kubectl-context.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kubectl-context.sh"
    mode: 0755
