---

- name: ensure project build directory is present
  file:
    state: directory
    path: "{{ kops_default_build_directory}}/{{ cluster.name }}"

- name: generate cluster.yml
  template:
    src: cluster.yml.j2
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/cluster.yml"
    mode: 0644

- name: generate instance-groups.yml
  template:
    src: instance-groups.yml.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/instance-groups.yml"
    mode: 0644

- name: generate ssh-key.pub
  template:
    src: ssh-key.pub.j2
    dest: "{{ kops_default_build_directory}}/{{ cluster.name }}/ssh-key.pub"
    mode: 0644

- name: generate kops-create.sh
  template:
    src: kops-create.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-create.sh"
    mode: 0755

- name: generate kops-update.sh
  template:
    src: kops-update.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-update.sh"
    mode: 0755

- name: generate kops-validate.sh
  template:
    src: kops-validate.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-validate.sh"
    mode: 0755

- name: generate kops-delete.sh
  template:
    src: kops-delete.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kops-delete.sh"
    mode: 0755

- name: generate kubectl-context.sh
  template:
    src: kubectl-context.sh.j2
    dest: "{{ kops_default_build_directory }}/{{ cluster.name }}/kubectl-context.sh"
    mode: 0755
